### PR TITLE
Refactor/add GitHub client

### PR DESCRIPTION
**Pull request by dpavicic**
Extending GitHub library with OctoKit client and RepositoryInfo

### CODE REVIEW

**Comment by thomhurst** [comment]
Can you add a doc about initialising the Octo client?

**Comment by thomhurst** [comment]
Also in the ModularPipelines.Build/ReleaseNotes.md file can you add a line or two summarizing your changes please

**Comment by dpavicic** [comment]
I was thinking of creating a separate PR for the docs update. Ok, I will add it to this PR.
Do you want it to be under some new/special category in the docs? Now, the docs have general parts of MP covered, but libraries such as this one, or dotnet, docker, etc., are not mentioned/have a category.

Regarding ReleaseNotes, ok.

**Comment by thomhurst** [comment]
> I was thinking of creating a separate PR for the docs update. Ok, I will add it to this PR. Do you want it to be under some new/special category in the docs? Now, the docs have general parts of MP covered, but libraries such as this one, or dotnet, docker, etc., are not mentioned/have a category.
> 
> Regarding ReleaseNotes, ok.

A new section would be great if that's okay

**Comment by dpavicic** [comment]
Added docs/release notes

**Comment by thomhurst** [comment]
Thanks for that! Unfortunately it looks like there's a DI problem (injecting scoped into singleton I think)

**Comment by dpavicic** [comment]
Any errors?
The only DI stuff is in the GitHubExtensions.cs where:

```csharp
public static IServiceCollection RegisterGitHubContext(this IServiceCollection services)
{
    services.TryAddScoped<IGitHub, GitHub>();
    services.TryAddScoped<IGitHubEnvironmentVariables, GitHubEnvironmentVariables>();
    **services.TryAddSingleton<IGitHubRepositoryInfo, GitHubRepositoryInfo>();**
    return services;
}
```

I needed to use `TryAddSingleton` since any other DI registration fails with:
"Service Provider Initializers are only supported for Singletons. GitHubRepositoryInfo is Scoped"

as only singletons allow post-registration initialization of services, we needed to use IInitializer to initialize the remote repo with awaits. But I don't have any errors when building the repo locally, and everything works ok.

If this is the error you are getting, do you have any thoughts?

**Comment by thomhurst** [comment]
@dpavicic This should sort it: https://github.com/six-tech/ModularPipelines/pull/2

**Comment by thomhurst** [comment]
Thanks for the contribution @dpavicic . New version will be out shortly :)

**Comment by dpavicic** [comment]
Great! Cheers :)

**Pull request merged**
